### 📝 Signup user
POST http://127.0.0.1:5000/api/signup
Content-Type: application/json

{
  "username": "eric",
  "email": "eric@example.com",
  "password": "12345",
  "role": "user"
}


### 🧑‍💼 Signup admin
POST http://127.0.0.1:5000/api/signup
Content-Type: application/json

{
  "username": "alice",
  "email": "alice@example.com",
  "password": "adminpass",
  "role": "admin"
}


### 🔐 Login user
POST http://127.0.0.1:5000/api/login
Content-Type: application/json

{
  "email": "eric@example.com",
  "password": "12345"
}


### 👤 Access profile (replace TOKEN below)
GET http://127.0.0.1:5000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1OTkxMjgxMSwianRpIjoiNjUyYzc0NzctNTkyZi00MDU0LTg4YjYtMDc2YmRkNWM2NTFhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNzU5OTEyODExLCJjc3JmIjoiNjg1MjA2NWQtMTBmYS00NmYzLWEyZjItZmQ0NmNkNWJkMDVhIiwiZXhwIjoxNzU5OTEzNzExfQ.vypk3ldfEi_TOUe7tfmv0qDTsv1qsj6__6kQKYUHxII
