### Signup
POST http://127.0.0.1:5000/api/signup
Content-Type: application/json

{
  "username": "eric",
  "email": "eric@example.com",
  "password": "12345"
}

### Login
POST http://127.0.0.1:5000/api/login
Content-Type: application/json

{
  "email": "eric@example.com",
  "password": "12345"
}

### Profile (replace token below)
GET http://127.0.0.1:5000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1OTgzMzczNiwianRpIjoiODUyMjA5NjItYjA5MC00OTI4LTlmYjQtOGJlNjA4M2Q5MmYzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNzU5ODMzNzM2LCJjc3JmIjoiNTI3ZmRjZTEtODE1Ny00MTY3LTg4ZWQtNmYxMGUyNmJjNGE1IiwiZXhwIjoxNzU5ODM0NjM2fQ.LdZDCh83xQk28ns4iR-DuZJOeJByvMxOQFgDOcGP5Yk
